DEFAULT_PIM_BASE_URL = "https://pim.plytix.com"
DEFAULT_AUTH_BASE_URL = "https://auth.plytix.com"

DEFAULT_HTTP_RETRIES = 3
DEFAULT_HTTP_TIMEOUT = 30

DEFAULT_PAGE_SIZE = 100
MAX_PAGE_SIZE = DEFAULT_PAGE_SIZE
