name: Upload Python Package

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: make requirements-tests
      - name: Run Integration Tests
        run: make integration-tests
        env:
          PLYTIX_API_KEY: ${{ secrets.PLYTIX_API_KEY }}
          PLYTIX_API_PASSWORD: ${{ secrets.PLYTIX_API_PASSWORD }}

  publish:
    needs:
      - tests
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/plytix-pim-client
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
